# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsHeadlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('source_website', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='email',
            new_name='index1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='password',
            new_name='index2',
        ),
    ]
