# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-17 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20161123_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.CharField(max_length=8)),
                ('Tag', models.CharField(max_length=255)),
                ('Count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='NewsHeadlines',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
